// Auto-generated by configure-network.bat
// Generated on: Sat 03/14/2026  9:09:08.83

class NetworkConfig {
  static const String localIP = '192.168.1.138';
  static const String backendUrl = 'http://192.168.1.138:3000/api';
  static const String healthUrl = 'http://192.168.1.138:3000/health';
}
